version: '3.8'

services:
  app:
    build: .
    container_name: flask_app
    ports:
      # - "80:80"
      - "5000:5000"
    restart: always
    networks:
      - demo-net
  db_dev:
    image: postgres:13.0-alpine
    volumes:
      - ../../demo-db-backups/demo_postgres_data_dev:/var/lib/postgresql/data/
    networks:
      - demo-net
    ports:
      - 5433:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}



networks:
  demo-net:
    driver: bridge
