user  root;

worker_processes  auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Logging
    access_log  /var/log/nginx/access.log;
    error_log   /var/log/nginx/error.log;

    # sendfile        on;
    # keepalive_timeout  65;

    # upstream xyz_backend {
    #     server 127.0.0.1:8001;
    #     server 127.0.0.1:8002;
    #     server 127.0.0.1:8003;
    #     # server 127.0.0.1:8005;
    # }

    # Your domains
    server {
        listen 80;
        server_name localhost;
        location / {
            proxy_pass http://localhost:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

# Default fallback
    server {
        listen 80 default_server;
        server_name _;
    
        root /usr/share/nginx/html;   # path to your fallback page
        index index.html;
    
        location / {
            try_files /index.html =404;
        }
    }
}
